const Exams = [
  {
    "denuntiation_date": "20/06/2023",
    "inspection_date": "20/06/2023",
    "inspection_time": "15:45:27",
    "accused_name": "Fulano de Tal",
    "report_number": "398476346",
    "report_address": "rua Street, número 100",
    "neighborhood": "Centro",
    "city": "Mariana",
    "responsible_for_completing": "Outro Fulano",
    "operating_mesoregion": "Sul",
    "species": "Canina",
    "gender": "Macho",
    "age": 1.3,
    "size": "Médio",
    "race": "Labrador",
    "pelage": "Castanho escuro",
    "animals_own_number": {
      "dog": 2,
      "cat": 0,
      "rabbit": 0,
      "horse": 0,
      "others": null,
    },
    "animal_observations": "observações",

    "body_condition": "Ideal",
    "has_fresh_water": "Sim",
    "animal_food": "Ração",
    "food_frequency": "4x ao dia",
    "drinking_condition": "Limpo",
    "feeder_condition": "Limpo",
    "nutritional_observations": "observações nutricionais",
    "opinion_regarding_nutritional": "Adequado",

    "has_fixed_shelter": "Sim",
    "has_weather_protection": "Sim",
    "has_comfort_to_rest": "Sim",
    "can_do_short_run": "Sim",
    "animal_per_species_numbers": "2x cachorros",
    "environment_and_containment_type": "Solto no quintal",
    "if_tied_is_released_some_time": "Sim",
    "surfaces_in_contact_with_the_animal": "Grama",
    "has_grass_or_ground_contact": "Sim",
    "are_poor_cleaning_conditions": "Não",
    "comfort_observations": "observações de conforto",
    "opinion_regarding_comfort": "Adequado",

    "animal_has_pain": "Não",
    "how_hes_walking": "Sim",
    "has_purulent_secretions": "Não",
    "has_diarrhea": "Não",
    "has_parasites_infestation": "Não",
    "pelage_conditions": "Brilhante e bem cuidada",
    "has_an_injury": "Não",
    "went_out_alone": "Não",
    "why_went_out_alone": null,
    "health_observations": "observações de saúde",
    "opinion_regarding_health": "Regular",

    "animal_things": {
      "dog_can_do_dog_things": "Sim",
      "cat_can_do_cat_things": null,
      "horse_can_do_horse_things": null,
    },
    "animal_alone_all_day": "Não",
    "are_there_others_animals": "Sim",
    "has_strange_behaviors": "Não",
    "is_the_animal_alert": "Não",
    "avoid_or_run_away_in_fear": "Não",
    "cart_driver_use_whip": null,
    "behavior_observations": "observações de comportamento",
    "opinion_regarding_behavior": "Regular",

    "inadequacy_of_which_indicators": null,
    "well_being_degree": "Alto",
    "incidents_of_mistreatment": "Não configura maus-tratos e não precisa de retorno",
    "generated_a_police_report": "Não",
  },
  {
    "denuntiation_date": "20/06/2023",
    "inspection_date": "20/06/2023",
    "inspection_time": "15:45:27",
    "accused_name": "Fulano de Tal",
    "report_number": "398476346",
    "report_address": "rua Street, número 100",
    "neighborhood": "Centro",
    "city": "Mariana",
    "responsible_for_completing": "Outro Fulano",
    "operating_mesoregion": "Sul",
    "species": "Canina",
    "gender": "Macho",
    "age": 1.3,
    "size": "Médio",
    "race": "Labrador",
    "pelage": "Castanho escuro",
    "animals_own_number": {
      "dog": 2,
      "cat": 0,
      "rabbit": 0,
      "horse": 0,
      "others": null,
    },
    "animal_observations": "observações",

    "body_condition": "Ideal",
    "has_fresh_water": "Sim",
    "animal_food": "Ração",
    "food_frequency": "4x ao dia",
    "drinking_condition": "Limpo",
    "feeder_condition": "Limpo",
    "nutritional_observations": "observações nutricionais",
    "opinion_regarding_nutritional": "Adequado",

    "has_fixed_shelter": "Sim",
    "has_weather_protection": "Sim",
    "has_comfort_to_rest": "Sim",
    "can_do_short_run": "Sim",
    "animal_per_species_numbers": "2x cachorros",
    "environment_and_containment_type": "Solto no quintal",
    "if_tied_is_released_some_time": "Sim",
    "surfaces_in_contact_with_the_animal": "Grama",
    "has_grass_or_ground_contact": "Sim",
    "are_poor_cleaning_conditions": "Não",
    "comfort_observations": "observações de conforto",
    "opinion_regarding_comfort": "Adequado",

    "animal_has_pain": "Não",
    "how_hes_walking": "Sim",
    "has_purulent_secretions": "Não",
    "has_diarrhea": "Não",
    "has_parasites_infestation": "Não",
    "pelage_conditions": "Brilhante e bem cuidada",
    "has_an_injury": "Não",
    "went_out_alone": "Não",
    "why_went_out_alone": null,
    "health_observations": "observações de saúde",
    "opinion_regarding_health": "Regular",

    "animal_things": {
      "dog_can_do_dog_things": "Sim",
      "cat_can_do_cat_things": null,
      "horse_can_do_horse_things": null,
    },
    "animal_alone_all_day": "Não",
    "are_there_others_animals": "Sim",
    "has_strange_behaviors": "Não",
    "is_the_animal_alert": "Não",
    "avoid_or_run_away_in_fear": "Não",
    "cart_driver_use_whip": null,
    "behavior_observations": "observações de comportamento",
    "opinion_regarding_behavior": "Regular",

    "inadequacy_of_which_indicators": null,
    "well_being_degree": "Alto",
    "incidents_of_mistreatment": "Não configura maus-tratos e não precisa de retorno",
    "generated_a_police_report": "Não",
  },
  {
    "denuntiation_date": "20/06/2023",
    "inspection_date": "20/06/2023",
    "inspection_time": "15:45:27",
    "accused_name": "Fulano de Tal",
    "report_number": "398476346",
    "report_address": "rua Street, número 100",
    "neighborhood": "Centro",
    "city": "Mariana",
    "responsible_for_completing": "Outro Fulano",
    "operating_mesoregion": "Sul",
    "species": "Canina",
    "gender": "Macho",
    "age": 1.3,
    "size": "Médio",
    "race": "Labrador",
    "pelage": "Castanho escuro",
    "animals_own_number": {
      "dog": 2,
      "cat": 0,
      "rabbit": 0,
      "horse": 0,
      "others": null,
    },
    "animal_observations": "observações",

    "body_condition": "Ideal",
    "has_fresh_water": "Sim",
    "animal_food": "Ração",
    "food_frequency": "4x ao dia",
    "drinking_condition": "Limpo",
    "feeder_condition": "Limpo",
    "nutritional_observations": "observações nutricionais",
    "opinion_regarding_nutritional": "Adequado",

    "has_fixed_shelter": "Sim",
    "has_weather_protection": "Sim",
    "has_comfort_to_rest": "Sim",
    "can_do_short_run": "Sim",
    "animal_per_species_numbers": "2x cachorros",
    "environment_and_containment_type": "Solto no quintal",
    "if_tied_is_released_some_time": "Sim",
    "surfaces_in_contact_with_the_animal": "Grama",
    "has_grass_or_ground_contact": "Sim",
    "are_poor_cleaning_conditions": "Não",
    "comfort_observations": "observações de conforto",
    "opinion_regarding_comfort": "Adequado",

    "animal_has_pain": "Não",
    "how_hes_walking": "Sim",
    "has_purulent_secretions": "Não",
    "has_diarrhea": "Não",
    "has_parasites_infestation": "Não",
    "pelage_conditions": "Brilhante e bem cuidada",
    "has_an_injury": "Não",
    "went_out_alone": "Não",
    "why_went_out_alone": null,
    "health_observations": "observações de saúde",
    "opinion_regarding_health": "Regular",

    "animal_things": {
      "dog_can_do_dog_things": "Sim",
      "cat_can_do_cat_things": null,
      "horse_can_do_horse_things": null,
    },
    "animal_alone_all_day": "Não",
    "are_there_others_animals": "Sim",
    "has_strange_behaviors": "Não",
    "is_the_animal_alert": "Não",
    "avoid_or_run_away_in_fear": "Não",
    "cart_driver_use_whip": null,
    "behavior_observations": "observações de comportamento",
    "opinion_regarding_behavior": "Regular",

    "inadequacy_of_which_indicators": null,
    "well_being_degree": "Alto",
    "incidents_of_mistreatment": "Não configura maus-tratos e não precisa de retorno",
    "generated_a_police_report": "Não",
  },
  {
    "denuntiation_date": "20/06/2023",
    "inspection_date": "20/06/2023",
    "inspection_time": "15:45:27",
    "accused_name": "Fulano de Tal",
    "report_number": "398476346",
    "report_address": "rua Street, número 100",
    "neighborhood": "Centro",
    "city": "Mariana",
    "responsible_for_completing": "Outro Fulano",
    "operating_mesoregion": "Sul",
    "species": "Canina",
    "gender": "Macho",
    "age": 1.3,
    "size": "Médio",
    "race": "Labrador",
    "pelage": "Castanho escuro",
    "animals_own_number": {
      "dog": 2,
      "cat": 0,
      "rabbit": 0,
      "horse": 0,
      "others": null,
    },
    "animal_observations": "observações",

    "body_condition": "Ideal",
    "has_fresh_water": "Sim",
    "animal_food": "Ração",
    "food_frequency": "4x ao dia",
    "drinking_condition": "Limpo",
    "feeder_condition": "Limpo",
    "nutritional_observations": "observações nutricionais",
    "opinion_regarding_nutritional": "Adequado",

    "has_fixed_shelter": "Sim",
    "has_weather_protection": "Sim",
    "has_comfort_to_rest": "Sim",
    "can_do_short_run": "Sim",
    "animal_per_species_numbers": "2x cachorros",
    "environment_and_containment_type": "Solto no quintal",
    "if_tied_is_released_some_time": "Sim",
    "surfaces_in_contact_with_the_animal": "Grama",
    "has_grass_or_ground_contact": "Sim",
    "are_poor_cleaning_conditions": "Não",
    "comfort_observations": "observações de conforto",
    "opinion_regarding_comfort": "Adequado",

    "animal_has_pain": "Não",
    "how_hes_walking": "Sim",
    "has_purulent_secretions": "Não",
    "has_diarrhea": "Não",
    "has_parasites_infestation": "Não",
    "pelage_conditions": "Brilhante e bem cuidada",
    "has_an_injury": "Não",
    "went_out_alone": "Não",
    "why_went_out_alone": null,
    "health_observations": "observações de saúde",
    "opinion_regarding_health": "Regular",

    "animal_things": {
      "dog_can_do_dog_things": "Sim",
      "cat_can_do_cat_things": null,
      "horse_can_do_horse_things": null,
    },
    "animal_alone_all_day": "Não",
    "are_there_others_animals": "Sim",
    "has_strange_behaviors": "Não",
    "is_the_animal_alert": "Não",
    "avoid_or_run_away_in_fear": "Não",
    "cart_driver_use_whip": null,
    "behavior_observations": "observações de comportamento",
    "opinion_regarding_behavior": "Regular",

    "inadequacy_of_which_indicators": null,
    "well_being_degree": "Alto",
    "incidents_of_mistreatment": "Não configura maus-tratos e não precisa de retorno",
    "generated_a_police_report": "Não",
  },
]